# Service Name and Port
spring.application.name=auth-service
server.port=8081

# Local MongoDB Connection String (Creates 'campus_hub' database automatically)
spring.data.mongodb.uri=mongodb://localhost:27017/campus_hub

# Connect to Eureka Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/