spring.application.name=event-service
server.port=8082

# MongoDB Database Location (Points to its own events collection)
spring.data.mongodb.uri=mongodb://localhost:27017/campushub_events

# Eureka Registration Address
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/